- type: job
  id: TaipanBotanist
  name: job-name-taipan-botanist
  description: job-description-taipan-botanist
  playTimeTracker: JobTaipanBotanist
  setPreference: false
  overrideConsoleVisibility: true
  isTaipan: true
  startingGear: TaipanBotanistGear
  icon: "JobIconTaipanBotanist"
  supervisors: job-supervisors-taipan-technical-supervisor
  canBeAntag: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Civilian
    time: 18000 # 5 hours
  - !type:RoleTimeRequirement
    role: JobBotanist
    time: 3600 # 1 hour
  access:
  - TaipanService
  - TaipanMaint
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
    - type: NpcFactionMember
      factions:
      - Taipan

- type: startingGear
  id: TaipanBotanistGear
  equipment:
    ears: ClothingHeadsetTaipan
    shoes: ClothingShoesBootsLaceup
    id: TaipanBotanistPDA
    socks: ClothingUnderwearSocksTaipanBotanist

- type: chameleonOutfit
  id: TaipanBotanistChameleonOutfit
  job: TaipanBotanist
  startingGear: TaipanBotanistGear
  equipment:
    id: PassengerPDA
    neck: ClothingNeckGoldmedal
