- type: job
  id: TaipanChef
  name: job-name-taipan-chef
  description: job-description-taipan-chef
  playTimeTracker: JobTaipanChef
  setPreference: false
  overrideConsoleVisibility: true
  isTaipan: true
  startingGear: TaipanChefGear
  icon: "JobIconTaipanChef"
  supervisors: job-supervisors-taipan-technical-supervisor
  canBeAntag: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Civilian
    time: 18000 # 5 hours
  - !type:RoleTimeRequirement
    role: JobChef
    time: 3600 # 1 hour
  - !type:RoleTimeRequirement
    role: JobBartender
    time: 3600 # 1 hour
  access:
  - TaipanService
  - TaipanMaint
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
    - type: NpcFactionMember
      factions:
      - Taipan

- type: startingGear
  id: TaipanChefGear
  equipment:
    ears: ClothingHeadsetTaipan
    shoes: ClothingShoesBootsLaceup
    id: TaipanChefPDA
    socks: ClothingUnderwearSocksTaipanChef

- type: chameleonOutfit
  id: TaipanChefChameleonOutfit
  job: TaipanChef
  startingGear: TaipanChefGear
  equipment:
    id: PassengerPDA
    neck: ClothingNeckGoldmedal
