- type: job
  id: TaipanMedic
  name: job-name-taipan-medic
  description: job-description-taipan-medic
  playTimeTracker: JobTaipanMedic
  setPreference: false
  overrideConsoleVisibility: true
  isTaipan: true
  startingGear: TaipanMedicGear
  icon: "JobIconTaipanMedic"
  supervisors: job-supervisors-taipan-research-director
  canBeAntag: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 36000 # 10 hours
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 18000 # 5 hours
  access:
  - TaipanMaint
  - TaipanMedical
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
    - type: NpcFactionMember
      factions:
      - Taipan

- type: startingGear
  id: TaipanMedicGear
  equipment:
    ears: ClothingHeadsetTaipan
    outerClothing: ClothingOuterTaipanCoatLabMed
    shoes: ClothingShoesColorWhite
    id: TaipanMedicPDA
    belt: ClothingBeltMedicalFilled
    socks: ClothingUnderwearSocksTaipanMedic

- type: chameleonOutfit
  id: TaipanMedicChameleonOutfit
  job: TaipanMedic
  startingGear: TaipanMedicGear
  equipment:
    id: PassengerPDA
    neck: ClothingNeckGoldmedal
