- type: job
  id: TaipanResearchDirector
  name: job-name-taipan-research-director
  description: job-description-taipan-research-director
  playTimeTracker: JobTaipanResearchDirector
  setPreference: false
  overrideConsoleVisibility: true
  isTaipan: true
  startingGear: TaipanResearchDirectorGear
  icon: "JobIconTaipanResearchDirector"
  supervisors: job-supervisors-syndicate
  canBeAntag: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Taipan
    time: 216000 # 60 hours
  - !type:RoleTimeRequirement
    role: JobTaipanResearcher
    time: 72000 # 20 hours
  - !type:RoleTimeRequirement
    role: JobTaipanMedic
    time: 36000 # 10 hours
  access:
  - TaipanAtmospherics
  - TaipanCargo
  - TaipanCommand
  - TaipanEngineering
  - TaipanMaint
  - TaipanMedical
  - TaipanResearchDirector
  - TaipanResearch
  - TaipanService
  - TaipanExternal
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
    - type: NpcFactionMember
      factions:
      - Taipan

- type: startingGear
  id: TaipanResearchDirectorGear
  equipment:
    eyes: ClothingEyesGlasses
    ears: ClothingHeadsetAltTaipan
    shoes: ClothingShoesBootsLaceup
    id: TaipanResearchDirectorPDA
    socks: ClothingUnderwearSocksTaipanResearchDirector

- type: chameleonOutfit
  id: TaipanResearchDirectorChameleonOutfit
  job: TaipanResearchDirector
  startingGear: TaipanResearchDirectorGear
  equipment:
    id: PassengerPDA
    neck: ClothingNeckGoldmedal
