- type: job
  id: TaipanTechnicalOperationsSupervisor
  name: job-name-taipan-technical-supervisor
  description: job-description-taipan-technical-supervisor
  playTimeTracker: JobTaipanTechnicalOperationsSupervisor
  setPreference: false
  overrideConsoleVisibility: true
  isTaipan: true
  startingGear: TaipanTechnicalOperationsSupervisorGear
  icon: "JobIconTaipanTechnicalOperationsSupervisor"
  supervisors: job-supervisors-syndicate
  canBeAntag: false
  requirements:
  - !type:RoleTimeRequirement
    role: JobTaipanCargotech
    time: 36000 # 10 hours
  - !type:RoleTimeRequirement
    role: JobTaipanAtmosphericsEngineer
    time: 18000 # 5 hours
  - !type:DepartmentTimeRequirement
    department: Taipan
    time: 144000 # 40 hours
  access:
  - TaipanAtmospherics
  - TaipanCargo
  - TaipanCommand
  - TaipanEngineering
  - TaipanMaint
  - TaipanMedical
  - TaipanResearch
  - TaipanService
  - TaipanTechnicalOperationsSupervisor
  - TaipanExternal
  special:
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplantTaipan ]
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
    - type: NpcFactionMember
      factions:
      - Taipan

- type: startingGear
  id: TaipanTechnicalOperationsSupervisorGear
  equipment:
    ears: ClothingHeadsetAltTaipan
    shoes: ClothingShoesBootsLaceup
    id: TaipanTechnicalOperationsSupervisorPDA
    socks: ClothingUnderwearSocksTaipanTechnicalOperationsSupervisor

- type: chameleonOutfit
  id: TaipanTechnicalOperationsSupervisorChameleonOutfit
  job: TaipanTechnicalOperationsSupervisor
  startingGear: TaipanTechnicalOperationsSupervisorGear
  equipment:
    id: PassengerPDA
    neck: ClothingNeckGoldmedal
