- type: playTimeTracker
  id: Taipan

- type: playTimeTracker
  id: JobTaipanAtmosphericsEngineer

- type: playTimeTracker
  id: JobTaipanBotanist

- type: playTimeTracker
  id: JobTaipanCargotech

- type: playTimeTracker
  id: JobTaipanChef

- type: playTimeTracker
  id: JobTaipanCommunicationsOfficer

- type: playTimeTracker
  id: JobTaipanMedic

- type: playTimeTracker
  id: JobTaipanParamedic

- type: playTimeTracker
  id: JobTaipanRecruit

- type: playTimeTracker
  id: JobTaipanResearchDirector

- type: playTimeTracker
  id: JobTaipanResearcher

- type: playTimeTracker
  id: JobTaipanTechnician

- type: playTimeTracker
  id: JobTaipanTechnicalOperationsSupervisor
